apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application-example
spec:
  destination:
    name: ''
    namespace: demo
    server: 'https://kubernetes.default.svc'
  source:
    path: . #<your-git-path>
    plugin:
      name: argocd-vault-plugin
    repoURL: https://github.com/vndereye/ArgoCD.git #<your-public-git-repo>
    tagetRevision: main
  project: default
  syncPolicy:
    automated:
      selfHeal: true
