apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: demo
  labels:
    app: vault-agent-demo
spec:
  selector:
    matchLabels:
      app: vault-agent-demo
  replicas: 1
  template:
    metadata:
      annotations:
        # AGENT INJECTOR SETTINGS
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-kv-secret: "secret/hashiconf"
        vault.hashicorp.com/agent-inject-secret-kv-secret: |
          {{with secret "secret/hashiconf"}}{{ .Data | toJSONPretty }}{{ end }}
        # VAULT SETTINGS
        vault.hashicorp.com/role: "app"
        vault.hashicorp.com/tls-secret: "tls-test-client"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
      labels:
        app: vault-agent-demo
    spec:
      shareProcessNamespace: true
      serviceAccountName: app
      containers:
      - name: app
        image: jodonnellhashi/static-secrets-app:1.0.0
        imagePullPolicy: Always
        securityContext:
          runAsUser: 100
          runAsGroup: 1000
        env:
        - name: APP_SECRET_PATH
          value: "/vault/secrets/kv-secret"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: demo
  labels:
    app: vault-agent-demo

